name: Helm Lint and Template Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  helm-lint-template:
    name: 'Validate'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.12.0 # specify the Helm version you want to use

    - name: Run Helm Lint
      run: helm lint #./path/to/your/chart 

    - name: Run Helm Template
      run: helm template . #./path/to/your/chart
